export const APP_CONSTANTS = {
  DATE_FORMAT: 'YYYY/MM/DD',
  BACKEND_DATE_FORMAT: 'YYYY-MM-DD',
  BACKEND_CUSTOM_DATE_FORMAT: 'YYYY-MM-DD HH:mm:ss',

  DATE_FORMAT_YEAR_MONTH: 'MMMM-yyyy',
  CUSTOM_DATE_FORMAT: 'yyyy-MM-DD'
};

export const USER_STATUS_CONSTANTS = {
  LOGGED_OFF: 'LOGGED_OFF',
  CREDENTIALS_VERIFIED: 'CREDENTIAL_VERIFIED',
  PIN_VERIFIED: 'PIN_VERIFIED',
  LOGGED_IN: 'LOGGED_IN'
};
